name: Release to Maven Central

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
      CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${CENTRAL_USERNAME}</username>
                <password>${CENTRAL_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Prepare and Perform Release
        run: |
          mvn -B release:clean release:prepare release:perform -s ~/.m2/settings.xml -DskipTests=true
