name: Release and Deploy to Maven Central

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Java and Maven Central credentials
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN
          
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          
      - name: Configure Git user
        run: |
          git config --global user.email "abhijeet.techrepo@gmail.com"
          git config --global user.name "Abhijeet Rai"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/iFrugal/iFrugal-parent.git
          git config --global credential.helper store
          git remote -v  # Verify
          git pull origin master
          
      - name: Verify settings.xml generated by setup-java
        run: cat ~/.m2/settings.xml
        
      - name: Build and verify
        run: mvn -B verify
        
      - name: Release and Deploy to Maven Central
        run: |
          mvn -B -s ~/.m2/settings.xml \
            -Darguments="-Dmaven.test.skip=true" \
            -DscmCommentPrefix="[release] [skip ci] " \
            release:clean release:prepare release:perform
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
